# Generated by Django 3.2 on 2021-11-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='aboutimage',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image1',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='storyimage',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='teamimage',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='whyusimage',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image1',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.URLField(blank=True, max_length=350),
        ),
    ]
