# Generated by Django 3.2 on 2021-11-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.URLField(blank=True, max_length=350),
        ),
    ]
